fix Lighthouse CI run

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,12 +1,20 @@
-name: Lighthouse
+name: Build project and Run Lighthouse CI
 on: push
 jobs:
-  static-dist-dir:
+  lhci:
+    name: Lighthouse CI
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1
-      - name: Run Lighthouse against a static dist dir
-        uses: treosh/lighthouse-ci-action@v2
-        with:
-          # no urls needed, since it uses local folder to scan .html files
-          configPath: './lighthouserc.json'
+      - name: Use Node.js 10.x
+          uses: actions/setup-node@v1
+          with:
+            node-version: 10.x
+            - name: npm install, build
+              run: |
+                npm install
+                npm run build
+            - name: run Lighthouse CI
+              run: |
+                npm install -g @lhci/cli@0.3.x
+                lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
