fix Lighthouse CI run

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,14 +7,14 @@ jobs:
     steps:
       - uses: actions/checkout@v1
       - name: Use Node.js 10.x
-          uses: actions/setup-node@v1
-          with:
-            node-version: 10.x
-            - name: npm install, build
-              run: |
-                npm install
-                npm run build
-            - name: run Lighthouse CI
-              run: |
-                npm install -g @lhci/cli@0.3.x
-                lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
+        uses: actions/setup-node@v1
+        with:
+          node-version: 10.x
+          - name: npm install, build
+            run: |
+              npm install
+              npm run build
+          - name: run Lighthouse CI
+            run: |
+              npm install -g @lhci/cli@0.3.x
+              lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
